/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as ManagerAnalyticsRouteImport } from './routes/manager.analytics'
import { Route as ManagerAssignmentsRouteImport } from './routes/manager.assignments'
import { Route as ManagerBookingsRouteImport } from './routes/manager.bookings'
import { Route as ManagerEscalationsRouteImport } from './routes/manager.escalations'
import { Route as ManagerHelpRouteImport } from './routes/manager.help'
import { Route as ManagerOperationsRouteImport } from './routes/manager.operations'
import { Route as ManagerProvidersRouteImport } from './routes/manager.providers'
import { Route as ManagerQualityRouteImport } from './routes/manager.quality'
import { Route as ManagerScheduleRouteImport } from './routes/manager.schedule'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAnalyticsRoute = ManagerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAssignmentsRoute = ManagerAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerBookingsRoute = ManagerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerEscalationsRoute = ManagerEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerHelpRoute = ManagerHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerOperationsRoute = ManagerOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerProvidersRoute = ManagerProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerQualityRoute = ManagerQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerScheduleRoute = ManagerScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ManagerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/provider': typeof ProviderRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/tracking': typeof TrackingRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/assignments': typeof ManagerAssignmentsRoute
  '/manager/bookings': typeof ManagerBookingsRoute
  '/manager/escalations': typeof ManagerEscalationsRoute
  '/manager/help': typeof ManagerHelpRoute
  '/manager/operations': typeof ManagerOperationsRoute
  '/manager/providers': typeof ManagerProvidersRoute
  '/manager/quality': typeof ManagerQualityRoute
  '/manager/schedule': typeof ManagerScheduleRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/provider': typeof ProviderRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/tracking': typeof TrackingRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/assignments': typeof ManagerAssignmentsRoute
  '/manager/bookings': typeof ManagerBookingsRoute
  '/manager/escalations': typeof ManagerEscalationsRoute
  '/manager/help': typeof ManagerHelpRoute
  '/manager/operations': typeof ManagerOperationsRoute
  '/manager/providers': typeof ManagerProvidersRoute
  '/manager/quality': typeof ManagerQualityRoute
  '/manager/schedule': typeof ManagerScheduleRoute
  '/manager': typeof ManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/provider': typeof ProviderRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/tracking': typeof TrackingRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/assignments': typeof ManagerAssignmentsRoute
  '/manager/bookings': typeof ManagerBookingsRoute
  '/manager/escalations': typeof ManagerEscalationsRoute
  '/manager/help': typeof ManagerHelpRoute
  '/manager/operations': typeof ManagerOperationsRoute
  '/manager/providers': typeof ManagerProvidersRoute
  '/manager/quality': typeof ManagerQualityRoute
  '/manager/schedule': typeof ManagerScheduleRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookings'
    | '/help'
    | '/login'
    | '/manager'
    | '/provider'
    | '/services'
    | '/support'
    | '/tracking'
    | '/manager/analytics'
    | '/manager/assignments'
    | '/manager/bookings'
    | '/manager/escalations'
    | '/manager/help'
    | '/manager/operations'
    | '/manager/providers'
    | '/manager/quality'
    | '/manager/schedule'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bookings'
    | '/help'
    | '/login'
    | '/provider'
    | '/services'
    | '/support'
    | '/tracking'
    | '/manager/analytics'
    | '/manager/assignments'
    | '/manager/bookings'
    | '/manager/escalations'
    | '/manager/help'
    | '/manager/operations'
    | '/manager/providers'
    | '/manager/quality'
    | '/manager/schedule'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookings'
    | '/help'
    | '/login'
    | '/manager'
    | '/provider'
    | '/services'
    | '/support'
    | '/tracking'
    | '/manager/analytics'
    | '/manager/assignments'
    | '/manager/bookings'
    | '/manager/escalations'
    | '/manager/help'
    | '/manager/operations'
    | '/manager/providers'
    | '/manager/quality'
    | '/manager/schedule'
    | '/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookingsRoute: typeof BookingsRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  ProviderRoute: typeof ProviderRoute
  ServicesRoute: typeof ServicesRoute
  SupportRoute: typeof SupportRoute
  TrackingRoute: typeof TrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/analytics': {
      id: '/manager/analytics'
      path: '/analytics'
      fullPath: '/manager/analytics'
      preLoaderRoute: typeof ManagerAnalyticsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/assignments': {
      id: '/manager/assignments'
      path: '/assignments'
      fullPath: '/manager/assignments'
      preLoaderRoute: typeof ManagerAssignmentsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/bookings': {
      id: '/manager/bookings'
      path: '/bookings'
      fullPath: '/manager/bookings'
      preLoaderRoute: typeof ManagerBookingsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/escalations': {
      id: '/manager/escalations'
      path: '/escalations'
      fullPath: '/manager/escalations'
      preLoaderRoute: typeof ManagerEscalationsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/help': {
      id: '/manager/help'
      path: '/help'
      fullPath: '/manager/help'
      preLoaderRoute: typeof ManagerHelpRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/operations': {
      id: '/manager/operations'
      path: '/operations'
      fullPath: '/manager/operations'
      preLoaderRoute: typeof ManagerOperationsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/providers': {
      id: '/manager/providers'
      path: '/providers'
      fullPath: '/manager/providers'
      preLoaderRoute: typeof ManagerProvidersRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/quality': {
      id: '/manager/quality'
      path: '/quality'
      fullPath: '/manager/quality'
      preLoaderRoute: typeof ManagerQualityRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/schedule': {
      id: '/manager/schedule'
      path: '/schedule'
      fullPath: '/manager/schedule'
      preLoaderRoute: typeof ManagerScheduleRouteImport
      parentRoute: typeof ManagerRoute
    }
  }
}

interface ManagerRouteChildren {
  ManagerAnalyticsRoute: typeof ManagerAnalyticsRoute
  ManagerAssignmentsRoute: typeof ManagerAssignmentsRoute
  ManagerBookingsRoute: typeof ManagerBookingsRoute
  ManagerEscalationsRoute: typeof ManagerEscalationsRoute
  ManagerHelpRoute: typeof ManagerHelpRoute
  ManagerOperationsRoute: typeof ManagerOperationsRoute
  ManagerProvidersRoute: typeof ManagerProvidersRoute
  ManagerQualityRoute: typeof ManagerQualityRoute
  ManagerScheduleRoute: typeof ManagerScheduleRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerAnalyticsRoute: ManagerAnalyticsRoute,
  ManagerAssignmentsRoute: ManagerAssignmentsRoute,
  ManagerBookingsRoute: ManagerBookingsRoute,
  ManagerEscalationsRoute: ManagerEscalationsRoute,
  ManagerHelpRoute: ManagerHelpRoute,
  ManagerOperationsRoute: ManagerOperationsRoute,
  ManagerProvidersRoute: ManagerProvidersRoute,
  ManagerQualityRoute: ManagerQualityRoute,
  ManagerScheduleRoute: ManagerScheduleRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookingsRoute: BookingsRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRouteWithChildren,
  ProviderRoute: ProviderRoute,
  ServicesRoute: ServicesRoute,
  SupportRoute: SupportRoute,
  TrackingRoute: TrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
